[build]
  publish = "."
  command = "echo 'No build step required'"

# Global headers for performance & security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    cache-control = "public, max-age=300"

# Cache static assets longer
[[headers]]
  for = "/css/*"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"

# SPA routing handled by _redirects file
# Removed redirect rules to avoid conflict with _redirects file
